### ISSUE TITLE
找不到 rancher.hidocker.io 的伺服器 DNS 位址

### ISSUE THREAD

**Issue by bestlong** [martinliu/rancher-docs#34]

**Comment by choldrim** [comment]
上次在微信群还说到了这个呢，是域名过期了...

**Comment by martinliu** [comment]
请访问 http://martinliu.github.io/  以前 hidocker.io 的域名过期了，由于没有经历继续维护，确定放弃这个域名。所有以前的信息都在  http://martinliu.github.io/
